version: '3.3'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: >  
     bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 conf.wsgi"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=genadb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/food/static
      - media_volume:/food/media

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/


volumes:
  static_volume:
  media_volume: