version: '3.3'
services:


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/food/static
      - media_volume:/food/media

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/


volumes:
  static_volume:
  media_volume: