# Generated by Django 4.0 on 2024-03-05 08:48
import json
from django.db import migrations


def add_product(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    #with open('../../../data/ingredients.json', 'r', encoding='utf-8') as file:
    with open('D:/foodgram/data/ingredients.json', 'r', encoding='utf-8') as file:
        ingredient_list = json.load(file)
        for ingredient in ingredient_list:
            Ingredient.objects.create(name=ingredient['name'],
                                  measurement_unit=ingredient['measurement_unit'])

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_product)
    ]
