# Generated by Django 4.0 on 2024-02-06 18:04
import json

from django.apps import apps
from django.db import migrations
from recipes.data_product import product


def add_product(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    for ingr in product:
        Ingredient.objects.create(name=ingr['name'],
                                  measurement_unit=ingr['measurement_unit'])


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_delete_color'),
    ]

    operations = [
        migrations.RunPython(add_product),
    ]
#
# with open('../../../data/ingredients.json', 'r') as file:
#     data = json.load(file)


#
# import json
#
#
# with open('../../../data/ingredients.json', 'r', encoding='utf-8') as file:
#     data = json.load(file)
#     print(data)
